// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebHocTap.Models;

#nullable disable

namespace WebHocTap.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220605213838_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebHocTap.Models.DiemSinhVien", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Diem")
                        .HasColumnType("float");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HinhThucID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LopID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MonID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayKT")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SinhVienID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("HinhThucID");

                    b.HasIndex("LopID");

                    b.HasIndex("MonID");

                    b.HasIndex("SinhVienID");

                    b.ToTable("Diem");
                });

            modelBuilder.Entity("WebHocTap.Models.HinhThuc", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenHinhThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("HinhThuc");
                });

            modelBuilder.Entity("WebHocTap.Models.KhoaHoc", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NienKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenKhoaHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("KhoaHoc");
                });

            modelBuilder.Entity("WebHocTap.Models.Lop_MonHoc", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LopID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MonHocID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("SoTiet")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ThoiGian")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("LopID");

                    b.HasIndex("MonHocID");

                    b.ToTable("Lop_MonHoc");
                });

            modelBuilder.Entity("WebHocTap.Models.Lop_SinhVien", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LopID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SinhVienID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("LopID");

                    b.HasIndex("SinhVienID");

                    b.ToTable("Lop_SinhVien");
                });

            modelBuilder.Entity("WebHocTap.Models.LopHoc", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GiaoVienID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("KhoaHocID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThoiLuong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("GiaoVienID");

                    b.HasIndex("KhoaHocID");

                    b.ToTable("Lop");
                });

            modelBuilder.Entity("WebHocTap.Models.MonHoc", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenMonHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Mon");
                });

            modelBuilder.Entity("WebHocTap.Models.Permission", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenPermission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("WebHocTap.Models.ThiKiemTra", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HinhThucID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LopID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MonHocID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("NgayKiemTra")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("ThoiLuong")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("HinhThucID");

                    b.HasIndex("LopID");

                    b.HasIndex("MonHocID");

                    b.ToTable("HinhThuc_Thi_KiemTra");
                });

            modelBuilder.Entity("WebHocTap.Models.User", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PermissionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Sdt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PermissionID");

                    b.ToTable("User");
                });

            modelBuilder.Entity("WebHocTap.Models.DiemSinhVien", b =>
                {
                    b.HasOne("WebHocTap.Models.HinhThuc", "HinhThuc")
                        .WithMany()
                        .HasForeignKey("HinhThucID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebHocTap.Models.LopHoc", "Lop")
                        .WithMany()
                        .HasForeignKey("LopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebHocTap.Models.MonHoc", "Mon")
                        .WithMany()
                        .HasForeignKey("MonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebHocTap.Models.User", "SinhVien")
                        .WithMany()
                        .HasForeignKey("SinhVienID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("HinhThuc");

                    b.Navigation("Lop");

                    b.Navigation("Mon");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("WebHocTap.Models.Lop_MonHoc", b =>
                {
                    b.HasOne("WebHocTap.Models.LopHoc", "Lop")
                        .WithMany()
                        .HasForeignKey("LopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebHocTap.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lop");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("WebHocTap.Models.Lop_SinhVien", b =>
                {
                    b.HasOne("WebHocTap.Models.LopHoc", "Lop")
                        .WithMany()
                        .HasForeignKey("LopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebHocTap.Models.User", "SinhVien")
                        .WithMany()
                        .HasForeignKey("SinhVienID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Lop");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("WebHocTap.Models.LopHoc", b =>
                {
                    b.HasOne("WebHocTap.Models.User", "GiaoVien")
                        .WithMany()
                        .HasForeignKey("GiaoVienID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebHocTap.Models.KhoaHoc", "KhoaHoc")
                        .WithMany()
                        .HasForeignKey("KhoaHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GiaoVien");

                    b.Navigation("KhoaHoc");
                });

            modelBuilder.Entity("WebHocTap.Models.ThiKiemTra", b =>
                {
                    b.HasOne("WebHocTap.Models.HinhThuc", "HinhThuc")
                        .WithMany()
                        .HasForeignKey("HinhThucID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebHocTap.Models.LopHoc", "Lop")
                        .WithMany()
                        .HasForeignKey("LopID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebHocTap.Models.MonHoc", "MonHoc")
                        .WithMany()
                        .HasForeignKey("MonHocID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HinhThuc");

                    b.Navigation("Lop");

                    b.Navigation("MonHoc");
                });

            modelBuilder.Entity("WebHocTap.Models.User", b =>
                {
                    b.HasOne("WebHocTap.Models.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");
                });
#pragma warning restore 612, 618
        }
    }
}
